config/routes.rb
Gaga::Application.routes.draw do
  resources :zhihus

end

app/models/zhihu.rb
class Zhihu < ActiveRecord::Base
  attr_accessible :answer, :desc, :tags, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/zhihus_controller.rb
class ZhihusController < ApplicationController
  # GET /zhihus
  # GET /zhihus.json
  def index
    @zhihus = Zhihu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zhihus }
    end
  end

  # GET /zhihus/1
  # GET /zhihus/1.json
  def show
    @zhihu = Zhihu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zhihu }
    end
  end

  # GET /zhihus/new
  # GET /zhihus/new.json
  def new
    @zhihu = Zhihu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zhihu }
    end
  end

  # GET /zhihus/1/edit
  def edit
    @zhihu = Zhihu.find(params[:id])
  end

  # POST /zhihus
  # POST /zhihus.json
  def create
    @zhihu = Zhihu.new(params[:zhihu])

    respond_to do |format|
      if @zhihu.save
        format.html { redirect_to @zhihu, notice: 'Zhihu was successfully created.' }
        format.json { render json: @zhihu, status: :created, location: @zhihu }
      else
        format.html { render action: "new" }
        format.json { render json: @zhihu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zhihus/1
  # PUT /zhihus/1.json
  def update
    @zhihu = Zhihu.find(params[:id])

    respond_to do |format|
      if @zhihu.update_attributes(params[:zhihu])
        format.html { redirect_to @zhihu, notice: 'Zhihu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zhihu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zhihus/1
  # DELETE /zhihus/1.json
  def destroy
    @zhihu = Zhihu.find(params[:id])
    @zhihu.destroy

    respond_to do |format|
      format.html { redirect_to zhihus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zhihus_helper.rb
# coding: utf-8
require 'nokogiri'
require 'open-uri'
require 'iconv'
module ZhihusHelper
    # extract the title and answer in the body of the url.
	def extract(url)
        puts url

        # extract title

        # extract desc
        # extract tags
        # extract answer
        doc = Nokogiri::HTML(open(url))
        puts Iconv.iconv("UTF-8", doc.to_s.encoding.to_s, doc) 
        #puts doc
        # 获取页面上所有的链接
        doc.css('a').each do |link|
          puts "#{link.content}, #{link['href']}"
        end

        # 打出 meta-keywords
        # puts doc.css("meta[name='keywords']")[0].content
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gaga</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zhihus/_form.html.erb
<%= form_for(@zhihu) do |f| %>
  <% if @zhihu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zhihu.errors.count, "error") %> prohibited this zhihu from being saved:</h2>

      <ul>
      <% @zhihu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zhihus/edit.html.erb
<h1>Editing zhihu</h1>

<%= render 'form' %>

<%= link_to 'Show', @zhihu %> |
<%= link_to 'Back', zhihus_path %>

app/views/zhihus/index.html.erb
<h1>Listing zhihus</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Tags</th>
    <th>Desc</th>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zhihus.each do |zhihu| %>
  <tr>
    <td><%= zhihu.title %></td>
    <td><%= zhihu.tags %></td>
    <td><%= zhihu.desc %></td>
    <td><%= zhihu.answer %></td>
    <td><%= link_to 'Show', zhihu %></td>
    <td><%= link_to 'Edit', edit_zhihu_path(zhihu) %></td>
    <td><%= link_to 'Destroy', zhihu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zhihu', new_zhihu_path %>

app/views/zhihus/new.html.erb
<h1>New zhihu</h1>

<%= render 'form' %>

<%= link_to 'Back', zhihus_path %>

app/views/zhihus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @zhihu.title %>
</p>

<p>
  <b>Tags:</b>
  <%= @zhihu.tags %>
</p>

<p>
  <b>Desc:</b>
  <%= @zhihu.desc %>
</p>

<p>
  <b>Answer:</b>
  <%= @zhihu.answer %>
</p>


<%= link_to 'Edit', edit_zhihu_path(@zhihu) %> |
<%= link_to 'Back', zhihus_path %>